name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read file #usage of multiline command
          run: |
            echo "My first github Action Job"
            ls -ltra
            cat README.md
        
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
        
        # - name: List files
        #   run: ls
        
        # - name: Read File
        #   run: cat README.md