name: Multiple job workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
    
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, i am a DRAGON..." > dragon.txt

    - name: upload Dragon test file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-test-file
        path: dragon.txt

  test_job_1:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: downlaod Dragon test file
      uses: actions/download-artifact@v4
      with:
        name: dragon-test-file
    
    - name: Test File exists
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_1
    runs-on: ubuntu-latest
    steps:        
    - name: downlaod Dragon test file
      uses: actions/download-artifact@v4
      with:
        name: dragon-test-file

    - name: Read File
      run: cat dragon.txt
    
    - name: Deploy
      run: echo Deploying........