name: Exploring variables and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker login
      env:
        DOCKER_PASSWORD: s3cUrePaSsw0rd
      run: docker login --username=${{ env.DOCKER_USERNAME }} --password= $DOCKER_PASSWORD

    - name: Docker Publish
      run: docker push docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
