name: Exploring workflow filters

on:
  workflow_dispatch:
  push:
    # branches-ignore:
    #   - feature/* #feature/add-music, feature/updateImages
    #   - test/**   #test/ui.index, test/checkout/pyament
    branches:
      - main 
      - '!feature/*' #ingoring pushing to any branch name starting with feature using !
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Step to perform
      run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}